Controllers/BukuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryWeb.Controllers
{
    public class BukuController : Controller
    {
        // GET: Buku
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title | Perpustakaan Web</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    @Styles.Render("~/assets/css")
    @Scripts.Render("~/assets/pace")
</head>
<body data-spy="scroll" data-target="#header-navbar" data-offset="51">
    <!-- begin #page-container -->
    <div id="page-container" class="fade">
        <!-- begin #header -->
        <div id="header" class="header navbar navbar-default navbar-fixed-top">
            <!-- begin container -->
            <div class="container">
                <!-- begin navbar-header -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/" class="navbar-brand">
                        <span class="brand-logo"></span>
                        <span class="brand-text">
                            <span class="text-theme">Perpustakaan</span> Web
                        </span>
                    </a>
                </div>
                <!-- end navbar-header -->
                <!-- begin navbar-collapse -->
                <div class="collapse navbar-collapse" id="header-navbar">
                    <ul class="nav navbar-nav navbar-right">
                        @if (Convert.ToString(this.Session["Role"]) == "A")
                        {
                            <li><a href="@Url.Action("Index", "Buku")">Buku</a></li>
                            <li><a href="@Url.Action("Index", "Account")">User</a></li>
                            <li><a href="@Url.Action("Index", "Pinjam")">Peminjaman</a></li>
                            <li><a href="@Url.Action("Index", "Kembali")">Pengembalian</a></li>
                            <li><a href="@Url.Action("LogOff", "Account", Url.Action("Login", "Account"))">Log Off</a></li>
                        }
                        else
                        {
                            <li><a href="@Url.Action("Register", "Home")">Daftar</a></li>
                            <li><a href="@Url.Action("Login", "Account")">Login</a></li>
                        }
                    </ul>
                </div>
                <!-- end navbar-collapse -->
            </div>
            <!-- end container -->
        </div>
        <!-- end #header -->
        <!-- begin #home -->
        <div class="container" style="padding-top:80px">
            @RenderBody()
        </div>
        <!-- end #home -->
    </div>
    <!-- end #page-container -->
    
    @Scripts.Render("~/assets/js")

    <script>
        $(document).ready(function () {
	        App.init();
        });
    </script>
</body>
</html>